version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
loggers:
  sample_run:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  semantic_chunking:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
    level: WARNING
    handlers: [console]
    propagate: no