[project]
name = "hierarchical-semantic-chunking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.0",
]
